Use new VirtDisk::FileIo interface for spec suite block operations
ManageIQ/virtfs-ext3 pull request #3
Opened 2017-09-01 21:09 UTC by movitto

2017-09-01 21:09 UTC, movitto commented
@roliveri similar comment to that w/ virtfs-fat32 wrt using the new VirtDisk interface

2017-09-01 22:28 UTC, roliveri requested changes

2017-09-01 22:28 UTC, roliveri commented on spec/spec_helper.rb
> +    block_dev = VirtFS::BlockIO.new(VirtDisk::FileIo.new(@ext.path))
@movitto 
This should be:
```ruby
block_dev = VirtDisk::Disk.new(VirtDisk::FileIo.new(@ext.path))
```
If the disk has partitions, the following will return an array of partitions on the disk:
```ruby
VirtDisk::PartitionType.partition_probe(blovk_dev)
```

2017-09-07 20:59 UTC, movitto commented
@roliveri got it, updated to use the new VirtDisk::Disk and VirtDisk::FileIo classes

2021-01-25 17:31 UTC, closed without merging